# Generated by Django 3.2.7 on 2021-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam_subscribe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
